name: your_environment_name
channels:
  - defaults
  - anaconda
  - plotly
dependencies:
  - python=3.12.2
  - pip
  - ipython
  - numpy
  - pandas
  - matplotlib
  - plotly
  - scikit-learn
  - networkx
  - statsmodels 
  - pip:
    - tqdm
    - pycountry
    - jupyterlab
    - lxml_html_clean
